// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCovqD6lnbS0id0DgWh2hypC7_EPe7pcaI',
    appId: '1:743268312226:web:3bd2f481ae62996015a3fb',
    messagingSenderId: '743268312226',
    projectId: 'econoapp-60ee3',
    authDomain: 'econoapp-60ee3.firebaseapp.com',
    storageBucket: 'econoapp-60ee3.firebasestorage.app',
    measurementId: 'G-8SQ14F9E34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3FUXu0sbCP9OEKk09A08veHOCVIZedZY',
    appId: '1:743268312226:android:06302a1ac1bb920415a3fb',
    messagingSenderId: '743268312226',
    projectId: 'econoapp-60ee3',
    storageBucket: 'econoapp-60ee3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxhM4TnTuKuP2bcHENYGwoq2hm0gf0Ykw',
    appId: '1:743268312226:ios:556eb6cf95de9f1815a3fb',
    messagingSenderId: '743268312226',
    projectId: 'econoapp-60ee3',
    storageBucket: 'econoapp-60ee3.firebasestorage.app',
    iosBundleId: 'com.example.econoapp',
  );

}